#1 Sprint 9
MaricTheirin/java-filmorate pull request #1
Opened 2023-01-09 11:42 UTC by MaricTheirin

2023-01-09 17:17 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Добавление нового фильма {}", film);
При отправке неверной даты, приходит ответ 500, но на самом деле это BadRequest 400, т.е. клиент прислал неверные данные, а не случилась ошибка на стороне сервера

500
{
	"timestamp": "2023-01-09T17:15:12.931482Z",
	"message": "Возникла ошибка при обработке запроса: Ошибка: информация о фильме заполнена некорректно"
}

2023-01-09 17:19 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User create(@Valid @RequestBody User user) {
Если отправить запрос без дня рождения, то приходит кусок stack trace. Похоже нужно добавить еще обработчик ошибки
{
	"timestamp": "2023-01-09T17:18:07.220059Z",
	"message": "Возникла ошибка при обработке запроса: JSON parse error: Cannot construct instance of `ru.yandex.practicum.filmorate.model.User`, problem: birthday is marked non-null but is null; nested exception is com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `ru.yandex.practicum.filmorate.model.User`, problem: birthday is marked non-null but is null\n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 5, column: 1]"
}

2023-01-09 17:22 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User update(@Valid @RequestBody User user) {
При обновлении пользователя не срабатывает обработчик исключения о том, что неверный email, но при создании он есть
{
	"timestamp": "2023-01-09T17:20:47.350085Z",
	"message": "Возникла ошибка при обработке запроса: Validation failed for argument [0] in public ru.yandex.practicum.filmorate.model.User ru.yandex.practicum.filmorate.controller.UserController.update(ru.yandex.practicum.filmorate.model.User): [Field error in object 'user' on field 'email': rejected value [wrong_emailmail.com]; codes [Email.user.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [user.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@737528ec,.*]; default message [must be a well-formed email address]] "
}

2023-01-09 17:24 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getId() == 0) {
если попробовать обновить пользователя, которого не существует, то приходит 500 ошибка
{
	"timestamp": "2023-01-09T17:23:17.121144Z",
	"message": "Возникла ошибка при обработке запроса: Ошибка: ID должен присваиваться автоматически"
}
Сообщение об ошибке лучше сделать другим, что такого пользователя не существует и код ошибки стоит изменить на более подходящий

2023-01-09 17:25 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Все работает по ТЗ.
Есть немного предложений как улучшить приложение, если есть желание

2023-01-09 19:56 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Добавление нового фильма {}", film);
Поправил, теперь выдаёт Bad request

2023-01-09 19:56 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User create(@Valid @RequestBody User user) {
Переработал формат вывода ошибок валидации, теперь они более дружелюбные

2023-01-09 19:57 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User update(@Valid @RequestBody User user) {
После исправлений не вопроизвелось

2023-01-09 19:57 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getId() == 0) {
Поправил, теперь сообщение корректно указывает на возникшую ошибку

2023-01-10 08:45 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-01-11 09:01 UTC, merged