Добавление списков друзей и лайков
MaricTheirin/java-filmorate pull request #2
Opened 2023-01-11 19:58 UTC by MaricTheirin

2023-01-12 07:45 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.save(user);
Если добавлять пользователя без дня рождения, то приходит сообщение об ошибке NullPointerException
{
	"timestamp": "2023-01-12T07:44:38.092796Z",
	"message": "Возникла ошибка при обработке запроса: java.lang.NullPointerException: birthday is marked non-null but is null"
}

2023-01-12 08:10 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично.
Странно, что можно добавить в друзья самого себя, но если это нормально по ТЗ, то ок.
Нашел всего одно замечание из разряда можно лучше.
Если есть желание, было бы здорово добавить тесты

2023-01-12 19:22 UTC, MaricTheirin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.save(user);
Заменено на более понятное сообщение

2023-01-13 16:18 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо, но принять не могу, т.к. не проходят проверки репозитория.
1s
Run REPO=$(curl -H "Accept: application/vnd.github+json" "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[1](https://github.com/MaricTheirin/java-filmorate/actions/runs/3905725341/jobs/6673090736#step:2:1)00 12094  100 12094    0     0  71319      0 --:--:-- --:--:-- --:--:-- 71562
Please set repository MaricTheirin/java-filmorate - PUBLIC
Error: Process completed with exit code [25](https://github.com/MaricTheirin/java-filmorate/actions/runs/3905725341/jobs/6673090736#step:2:26)3.

2023-01-13 16:49 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо

2023-01-14 16:51 UTC, merged